[package]
name = "libradium"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]

[dependencies]
rand = "0.3"
time = "0.1"

[[example]]
name = "main"

[features]
default = []
with-ticks = []