[package]
name = "libradium"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]

[dependencies]
rand = "0.3"
threadpool = "1.3"
byteorder = "1"
num_cpus = "1.0"
time = "0.1"