[package]
name = "radiumd"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]

[dependencies]
libradium = { path = "../libradium" }
radium_protocol = { path = "../radium_protocol" }
mio = "0.6"
slab = "0.3.0"